### PR TITLE
Add instructions for running with a shared cache on hipergator to REA…

### PR DESCRIPTION
**Pull request by diazrenata**
…DME.md

@ha0ye could you try this and see if you come across missing steps?

### CODE REVIEW

**Review by ha0ye — CHANGES_REQUESTED** [review]
Can you make a few minor modifications?
* use https://weecology.github.io/MATSS/articles/hipergator-install.html as the link for the vignette
* replace the install command from “devtools” to “remotes”

**Comment by diazrenata** [comment]
For sure on the link!

I actually had a lot of trouble getting “remotes” to run on Travis. I kept
getting “no package called remotes”, even when I put
install.packages(remotes) immediately ahead of calling remotes.

My guess was something about a package cache in Travis? Or something else?
:crystal_ball:

**Comment by ha0ye** [comment]
So, after many weeks and a lot of trial and error, I got the right Travis install for retriever, which was the initial error you ran into, so that change should be propagated here.

Other than that, I don’t think remotes or MATSS need to be installed in the Travis script, if they’re set up in DESCRIPTION appropriately.

**Comment by diazrenata** [comment]
>.> I just tried one with the same yml as the master branch, and I’m
getting the remotes error. I’ll investigate more later....this is
strange....

**Comment by diazrenata** [comment]
.......or not! The last one just passed. 🔮

**Comment by ha0ye** [comment]
I think you could remove the line from Travis.yml that uses remotes to install Weecology/MATSS.

**Comment by diazrenata** [comment]
@ha0ye You're right! It passed once I removed that line. 

I've updated the link now too, so I think this is good to go?

**Comment by ha0ye** [comment]
> @ha0ye You're right! It passed once I removed that line.
> 
> I've updated the link now too, so I think this is good to go?

Can you update the installation instructions to use `remotes::install_github()` instead of `devtools::install_github()`

**Review by ha0ye — APPROVED** [review]

**Pull request merged**
